### ISSUE TITLE
GitHub pages link

### ISSUE THREAD

**Issue by hingyimartin** [Teaching-projects/SZE-MOSZE-2020-Gateway#6]

**Comment by hegyhati** [comment]
Ezt egy kisse megkesve kertetek... illetve mi is a keres?!

**Comment by hingyimartin** [comment]
@hegyhati 
Elnézést. 
Szeretnénk kérni a github pages linkjét.

**Comment by vizvezetek** [comment]
@hmartin28 szerintem a pages settings-et szeretnéd kérni.

**Comment by hegyhati** [comment]
> @hegyhati
> Elnézést.
> Szeretnénk kérni a github pages linkjét.

https://pages.github.com/

**Comment by hegyhati** [comment]
beallitottam...
